spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://192.168.1.134:3306/db_reservas?serverTimezone=Europe/Madrid
    password: sasa
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9000
